package org.dylanjones.sleepradio.core.design

import android.graphics.Typeface
import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.Image
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.FilterQuality
import androidx.compose.ui.graphics.Shadow
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.imageResource
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import org.dylanjones.sleepradio.R

/** A rectangle in the sprite's own pixel space. */
data class ArtRect(val x: Float, val y: Float, val w: Float, val h: Float) {
    val right get() = x + w
    val bottom get() = y + h
}

/**
 * The geometry of the channel-button artwork (`res/drawable-nodpi/channel_key_*.webp`), in the
 * sprite's pixel space. Generated by `tools/keyart/make_keys.py` — see `regions.json` there; keep
 * these in step with it.
 */
object ChannelKeyArt {
    const val WIDTH = 560f
    const val HEIGHT = 236f

    /** The window the channel number sits in (lights up when playing). */
    val NUMBER = ArtRect(40f, 40f, 128f, 130f)

    /** The window the station name sits in. */
    val LABEL = ArtRect(182f, 46f, 262f, 118f)

    /** The lamp lens (centre and diameter) — part of the artwork, no text over it. */
    val LAMP = ArtRect(489f - 31f, 105f - 31f, 62f, 62f)

    /** How far lower a latched (pressed-in) key sits than an idle one, drawn into the artwork. */
    const val TRAVEL = 10f

    /** Extra sink while a finger is actually pressing it. */
    const val PRESS_EXTRA = 3f
}

private val Condensed = FontFamily(Typeface.create("sans-serif-condensed", Typeface.BOLD))
private val CondensedMedium = FontFamily(Typeface.create("sans-serif-condensed", Typeface.NORMAL))

private val NumberIdle = Color(0xFFE8DDC9)
private val NumberPaused = Color(0xFFF2CF93)
private val NumberLit = Color(0xFF2B1A06)
private val LabelIdle = Color(0xFFA89A80)
private val LabelPaused = Color(0xFFD3A866)
private val LabelLit = Color(0xFFFFDB9A)
private val LabelEmpty = Color(0xFF6F6453)
private const val FadeMs = 250

/**
 * A wide 1970s radio channel button, drawn from bitmap artwork: idle (stands proud), paused (pressed
 * in, dim amber) and playing (pressed in, number window and lamp lit). The three pictures cross-fade
 * and only the words are live — the number and the station name are laid over empty windows in the
 * artwork, so any name fits and the pictures never change. The artwork keeps its shape and is centred
 * in whatever space it is given; nothing about the layout changes with the state.
 *
 * @param lamp lamp intensity 0..1: how far the lit picture is blended over the dim one (a dim
 *   bedside setting), 1 = full.
 */
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun ChannelKey(
    number: Int,
    label: String,
    active: Boolean,
    playing: Boolean,
    contentDescription: String,
    onClick: () -> Unit,
    onLongClick: () -> Unit,
    modifier: Modifier = Modifier,
    empty: Boolean = false,
    lamp: Float = 1f,
) {
    val outArt = ImageBitmap.imageResource(R.drawable.channel_key_out)
    val dimArt = ImageBitmap.imageResource(R.drawable.channel_key_dim)
    val litArt = ImageBitmap.imageResource(R.drawable.channel_key_lit)

    val interaction = remember { MutableInteractionSource() }
    val pressed by interaction.collectIsPressedAsState()
    val paused = active && !playing

    val latch by animateFloatAsState(if (active) 1f else 0f, tween(FadeMs), label = "key-latch")
    val lit by animateFloatAsState(if (playing) 1f else 0f, tween(FadeMs), label = "key-lit")
    val press by animateFloatAsState(if (pressed) 1f else 0f, tween(80), label = "key-press")

    val numberColor by animateColorAsState(
        when { playing -> NumberLit; paused -> NumberPaused; else -> NumberIdle }, tween(FadeMs), label = "number",
    )
    val labelColor by animateColorAsState(
        when { playing -> LabelLit; paused -> LabelPaused; empty -> LabelEmpty; else -> LabelIdle },
        tween(FadeMs), label = "label",
    )

    BoxWithConstraints(
        modifier
            .semantics(mergeDescendants = true) {
                this.contentDescription = contentDescription
                role = Role.Button
            }
            .combinedClickable(
                interactionSource = interaction,
                indication = null, // the artwork's own depth is the feedback
                onClick = onClick,
                onLongClick = onLongClick,
            ),
        contentAlignment = Alignment.Center,
    ) {
        // dp per artwork pixel: fit the artwork inside the space we are given, keeping its shape.
        val scale = minOf(maxWidth.value / ChannelKeyArt.WIDTH, maxHeight.value / ChannelKeyArt.HEIGHT)
        val density = LocalDensity.current
        val artW = (ChannelKeyArt.WIDTH * scale).dp
        val artH = (ChannelKeyArt.HEIGHT * scale).dp
        val travelPx = with(density) { (ChannelKeyArt.TRAVEL * scale).dp.toPx() }
        val pressPx = with(density) { (ChannelKeyArt.PRESS_EXTRA * scale).dp.toPx() }
        // Text sizes follow the artwork (dp, not sp): they live inside fixed windows in a picture,
        // so a large system font size must not push them out of it.
        val numberSize = with(density) { (artW * 0.215f).toSp() }
        val labelSize = with(density) { (artW * 0.060f).toSp() }

        Box(Modifier.size(artW, artH).graphicsLayer { translationY = press * pressPx }) {
            Image(outArt, null, Modifier.fillMaxSize(), contentScale = ContentScale.FillBounds, alpha = 1f - latch, filterQuality = FilterQuality.High)
            Image(dimArt, null, Modifier.fillMaxSize(), contentScale = ContentScale.FillBounds, alpha = latch, filterQuality = FilterQuality.High)
            Image(litArt, null, Modifier.fillMaxSize(), contentScale = ContentScale.FillBounds, alpha = lit * lamp.coerceIn(0f, 1f), filterQuality = FilterQuality.High)

            // The live words move down with the artwork when it latches in.
            Box(Modifier.fillMaxSize().graphicsLayer { translationY = latch * travelPx }) {
                ArtText(ChannelKeyArt.NUMBER, scale) {
                    Text(
                        text = "$number",
                        color = numberColor,
                        fontFamily = Condensed,
                        fontSize = numberSize,
                        lineHeight = numberSize,
                        textAlign = TextAlign.Center,
                        style = TextStyle(
                            shadow = if (playing) {
                                Shadow(Color(0x88FFECBE), Offset(0f, 2f), 0f) // a lit numeral: soft highlight
                            } else {
                                Shadow(Color.Black, Offset(0f, 2f), 0f)        // engraved
                            },
                        ),
                    )
                }
                ArtText(ChannelKeyArt.LABEL, scale) {
                    Text(
                        text = label.uppercase(),
                        color = labelColor,
                        fontFamily = CondensedMedium,
                        fontSize = labelSize,
                        lineHeight = labelSize * 1.12f,
                        letterSpacing = labelSize * 0.05f,
                        textAlign = TextAlign.Center,
                        maxLines = 2,
                        overflow = TextOverflow.Ellipsis,
                        style = if (playing) {
                            TextStyle(shadow = Shadow(Color(0xCCFFA632), Offset.Zero, 14f))
                        } else {
                            TextStyle.Default
                        },
                    )
                }
            }
        }
    }
}

/** Centres [content] inside the artwork window [rect] (sprite pixels), scaled by [scale] dp per pixel. */
@Composable
private fun ArtText(rect: ArtRect, scale: Float, content: @Composable () -> Unit) {
    Box(
        Modifier
            .offset((rect.x * scale).dp, (rect.y * scale).dp)
            .size((rect.w * scale).dp, (rect.h * scale).dp),
        contentAlignment = Alignment.Center,
    ) { content() }
}
