package org.dylanjones.sleepradio.core.design

import android.graphics.Typeface
import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.basicMarquee
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.wrapContentHeight
import androidx.compose.foundation.layout.wrapContentSize
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.FilterQuality
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathOperation
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.Shadow
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.imageResource
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.rememberTextMeasurer
import androidx.compose.ui.text.style.LineBreak
import androidx.compose.ui.text.PlatformTextStyle
import androidx.compose.ui.text.style.LineHeightStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.Dp
import org.dylanjones.sleepradio.R
import org.dylanjones.sleepradio.core.data.ChannelButtonMode

/** A rectangle in the sprite's own pixel space. */
data class ArtRect(val x: Float, val y: Float, val w: Float, val h: Float) {
    val right get() = x + w
    val bottom get() = y + h
}

/**
 * The geometry of the channel-button artwork (`res/drawable-nodpi/channel_key_*.webp`), in the
 * sprite's pixel space. Generated by `tools/keyart/make_keys.py` — see `regions.json` there; keep
 * these in step with it.
 */
object ChannelKeyArt {
    const val WIDTH = 560f
    const val HEIGHT = 236f

    /** The window the channel number sits in (lights up when playing). */
    val NUMBER = ArtRect(40f, 40f, 128f, 130f)

    /** The window the station name sits in. */
    val LABEL = ArtRect(182f, 46f, 262f, 118f)

    /** The lamp lens (centre and diameter) — part of the artwork, no text over it. */
    val LAMP = ArtRect(489f - 31f, 105f - 31f, 62f, 62f)

    /** How far lower a latched (pressed-in) key sits than an idle one, drawn into the artwork. */
    const val TRAVEL = 10f

    /** Extra sink while a finger is actually pressing it. */
    const val PRESS_EXTRA = 3f

    /**
     * The font size (dp) that makes [digits] characters of the bold condensed face fill a window of
     * [windowW] x [windowH] dp: about the window's height for the glyph height, limited by the width.
     */
    fun fillFontSizeDp(digits: Int, windowW: Float, windowH: Float): Float =
        minOf(windowH * 1.15f, windowW / (digits.coerceAtLeast(1) * 0.55f))

    /** The one-big-button station-name size: about half the label window's height, so it reads at a glance. */
    fun bigLabelFontDp(windowHeightDp: Float): Float = windowHeightDp * BIG_LABEL_HEIGHT_FRACTION

    const val BIG_LABEL_HEIGHT_FRACTION = 0.5f

    /** The normal wide key. */
    val WIDE = KeyArt(
        WIDTH, HEIGHT, NUMBER, LABEL, LAMP,
        R.drawable.channel_key_out, R.drawable.channel_key_dim, R.drawable.channel_key_lit,
    )

    /**
     * The TALL key: the same key stood upright, for the full-screen channel button in portrait (see
     * `make_keys.py`'s `use_tall_geometry` and `tall_regions.json`). Number window at the top, a big
     * name window in the middle, the lamp at the bottom.
     */
    val TALL = KeyArt(
        width = 420f, height = 680f,
        number = ArtRect(135f, 42f, 150f, 130f),
        label = ArtRect(48f, 201f, 324f, 300f),
        lamp = ArtRect(210f - 40f, 572f - 40f, 80f, 80f),
        out = R.drawable.channel_key_tall_out, dim = R.drawable.channel_key_tall_dim, lit = R.drawable.channel_key_tall_lit,
    )

    /**
     * The BROAD key: the wide key stretched for the full-screen channel button in landscape (see
     * `make_keys.py`'s `use_broad_geometry` and `broad_regions.json`). A slimmer number plate, the
     * lamp, and a name window taller and half as wide again as the normal key's.
     */
    val BROAD = KeyArt(
        width = 680f, height = 236f,
        number = ArtRect(40f, 40f, 112f, 130f),
        label = ArtRect(166f, 30f, 398f, 150f),
        lamp = ArtRect(609f - 31f, 105f - 31f, 62f, 62f),
        out = R.drawable.channel_key_broad_out, dim = R.drawable.channel_key_broad_dim, lit = R.drawable.channel_key_broad_lit,
    )

    /** Average advance of the bold condensed face per character, in em, with the label's letter spacing. */
    const val CONDENSED_EM_PER_CHAR = 0.59f

    /** Line height of the tall key's name, as a multiple of the font size. */
    const val TALL_LINE_HEIGHT = 1.08f

    /**
     * The full-screen station-name size (dp): as large as fits [windowW] x [windowH] dp with the name
     * wrapped at spaces onto at most [maxLines] lines (3 in the tall key, 2 in the broad one), no word
     * broken, never scrolling; capped at 1/[maxLines] of the window's height, so a short name doesn't
     * turn into one giant word. [textWidth] is the width (dp) of one line of text at a font size (dp):
     * the app measures the real face (wide capitals like B, D, O and W are well over the average);
     * by default an estimate from [CONDENSED_EM_PER_CHAR].
     */
    fun fitLabelFontDp(
        label: String,
        windowW: Float,
        windowH: Float,
        maxLines: Int = 3,
        textWidth: (text: String, fontDp: Float) -> Float = { text, fontDp -> text.length * fontDp * CONDENSED_EM_PER_CHAR },
    ): Float {
        val words = label.trim().split(Regex("\\s+")).filter { it.isNotEmpty() }
        var size = windowH / maxLines
        if (words.isEmpty()) return size
        while (size > 4f) {
            val lines = wrapLines(words) { textWidth(it, size) <= windowW }
            if (lines != null && lines <= maxLines && lines * size * TALL_LINE_HEIGHT <= windowH) return size
            size *= 0.96f
        }
        return size
    }

    /** How many lines [words] take wrapped greedily at spaces, or null if a word alone doesn't [fits] a line. */
    private fun wrapLines(words: List<String>, fits: (String) -> Boolean): Int? {
        var lines = 1
        var line = ""
        for (w in words) {
            if (!fits(w)) return null
            line = when {
                line.isEmpty() -> w
                fits("$line $w") -> "$line $w"
                else -> { lines++; w }
            }
        }
        return lines
    }
}

/** One channel-key artwork: its size and windows in sprite pixels, and its three state pictures. */
class KeyArt(
    val width: Float,
    val height: Float,
    val number: ArtRect,
    val label: ArtRect,
    val lamp: ArtRect,
    val out: Int,
    val dim: Int,
    val lit: Int,
)

private val Condensed = FontFamily(Typeface.create("sans-serif-condensed", Typeface.BOLD))
private val CondensedMedium = FontFamily(Typeface.create("sans-serif-condensed", Typeface.NORMAL))

private val NumberIdle = Color(0xFFE8DDC9)
private val NumberPaused = Color(0xFFF2CF93)
private val NumberLit = Color(0xFF2B1A06)
private val LabelIdle = Color(0xFFA89A80)
private val LabelPaused = Color(0xFFD3A866)
private val LabelLit = Color(0xFFFFDB9A)
private val LabelEmpty = Color(0xFF6F6453)
private const val FadeMs = 250

/**
 * How brightly the keys' lamps and lit windows shine, 0.2..1 (the "Lamp brightness" setting). Every
 * key reads it, so it is provided once at the top of the screen; a lower value blends the lit
 * artwork down towards its dim version.
 */
val LocalLampBrightness = compositionLocalOf { 1f }

/** How the channel buttons are shown (the "Channel buttons" setting); read by the preset row. */
val LocalChannelButtonMode = compositionLocalOf { ChannelButtonMode.GRID }

/** A symbol that can sit in a key's lit window instead of a number. */
enum class KeyIcon { MOON, WAVE }

/**
 * A wide 1970s radio channel button, drawn from bitmap artwork: idle (stands proud), paused (pressed
 * in, dim amber) and playing (pressed in, number window and lamp lit). See [RadioKey].
 *
 * @param lamp lamp intensity 0..1: how far the lit picture is blended over the dim one (a dim
 *   bedside setting), 1 = full.
 */
@Composable
fun ChannelKey(
    number: Int,
    label: String,
    active: Boolean,
    playing: Boolean,
    contentDescription: String,
    onClick: () -> Unit,
    onLongClick: () -> Unit,
    modifier: Modifier = Modifier,
    empty: Boolean = false,
    lamp: Float = LocalLampBrightness.current,
    /** The one-big-button mode: bigger station name (two lines) for easier reading. */
    big: Boolean = false,
    /** The full-screen mode: the name wrapped and as large as it fits, never scrolling. */
    full: Boolean = false,
    /** ...and in portrait, on the upright key (in landscape it uses the broad key). */
    tall: Boolean = false,
) {
    RadioKey(
        label = label,
        art = when {
            tall -> ChannelKeyArt.TALL
            full -> ChannelKeyArt.BROAD
            else -> ChannelKeyArt.WIDE
        },
        bigScrollingLabel = big && !full,
        fitLabelLines = when { !full -> 0; tall -> 3; else -> 2 },
        active = active,
        lit = playing,
        contentDescription = contentDescription,
        onClick = onClick,
        onLongClick = onLongClick,
        modifier = modifier,
        labelEmpty = empty,
        lamp = lamp,
    ) { color, lit, windowHeight ->
        val size = with(LocalDensity.current) { (windowHeight * NUMBER_OF_WINDOW).toSp() }
        Text(
            text = "$number",
            color = color,
            fontFamily = Condensed,
            fontSize = size,
            lineHeight = size,
            textAlign = TextAlign.Center,
            style = TextStyle(
                // A lit numeral gets a soft highlight; an unlit one is engraved.
                shadow = if (lit) Shadow(Color(0x88FFECBE), Offset(0f, 2f), 0f) else Shadow(Color.Black, Offset(0f, 2f), 0f),
            ),
        )
    }
}

/**
 * SLEEP / NOISE: the same wide key with a [icon] in its window; [on] lights it, like a playing channel.
 * When [bigLabel] is set (e.g. the minutes left on the sleep timer) it replaces the small [label] and
 * is drawn as large as the label window allows.
 */
@Composable
fun ToggleKey(
    icon: KeyIcon,
    label: String,
    on: Boolean,
    contentDescription: String,
    onClick: () -> Unit,
    onLongClick: () -> Unit,
    modifier: Modifier = Modifier,
    lamp: Float = LocalLampBrightness.current,
    bigLabel: String? = null,
) {
    RadioKey(
        label = label,
        bigLabel = bigLabel,
        active = on,
        lit = on,
        contentDescription = contentDescription,
        onClick = onClick,
        onLongClick = onLongClick,
        modifier = modifier,
        lamp = lamp,
    ) { color, _, windowHeight ->
        KeyIconGlyph(icon, color, windowHeight * ICON_OF_WINDOW)
    }
}

/** The channel number's font size and the SLEEP/NOISE icon's size, as fractions of the number window's height. */
private const val NUMBER_OF_WINDOW = 0.926f
private const val ICON_OF_WINDOW = 0.603f

@Composable
private fun KeyIconGlyph(icon: KeyIcon, color: Color, size: Dp) {
    Canvas(Modifier.size(size)) {
        val r = this.size.minDimension / 2f
        when (icon) {
            KeyIcon.MOON -> {
                // A crescent: a disc with a second, offset disc cut out of it.
                val disc = Path().apply { addOval(Rect(center, r)) }
                val bite = Path().apply { addOval(Rect(Offset(center.x + r * 0.5f, center.y - r * 0.28f), r * 0.86f)) }
                drawPath(Path.combine(PathOperation.Difference, disc, bite), color)
            }
            KeyIcon.WAVE -> {
                val w = this.size.width
                val path = Path().apply {
                    moveTo(0f, center.y)
                    // two gentle periods across the width
                    for (i in 0..40) {
                        val t = i / 40f
                        lineTo(t * w, center.y - kotlin.math.sin(t * 4f * Math.PI.toFloat()) * r * 0.55f)
                    }
                }
                drawPath(path, color, style = Stroke(width = r * 0.34f, cap = StrokeCap.Round, join = StrokeJoin.Round))
            }
        }
    }
}

/**
 * The shared radio pushbutton: three bitmap pictures (idle / paused / lit) cross-faded by state, and
 * live words over the artwork's windows. [active] = latched in; [lit] = its lamp and window are lit
 * (an [active] key that is not [lit] is paused: dim amber). [window] draws whatever goes in the left
 * window — a number or an icon — given the colour it should use for the current state, whether it is
 * lit, and the drawn artwork width (for sizing in dp, not sp: it lives inside a picture).
 *
 * The artwork keeps its shape and is centred in whatever space it is given; nothing about the layout
 * changes with the state.
 */
@OptIn(ExperimentalFoundationApi::class)
@Composable
private fun RadioKey(
    label: String,
    active: Boolean,
    lit: Boolean,
    contentDescription: String,
    onClick: () -> Unit,
    onLongClick: () -> Unit,
    modifier: Modifier = Modifier,
    labelEmpty: Boolean = false,
    lamp: Float = LocalLampBrightness.current,
    bigLabel: String? = null,
    bigScrollingLabel: Boolean = false,
    /** When > 0: the name wrapped onto up to this many lines, as large as fits (the full-screen mode). */
    fitLabelLines: Int = 0,
    art: KeyArt = ChannelKeyArt.WIDE,
    window: @Composable (color: Color, lit: Boolean, windowHeight: Dp) -> Unit,
) {
    val outArt = ImageBitmap.imageResource(art.out)
    val dimArt = ImageBitmap.imageResource(art.dim)
    val litArt = ImageBitmap.imageResource(art.lit)

    val interaction = remember { MutableInteractionSource() }
    val pressed by interaction.collectIsPressedAsState()
    val paused = active && !lit

    val latch by animateFloatAsState(if (active) 1f else 0f, tween(FadeMs), label = "key-latch")
    val litLevel by animateFloatAsState(if (lit) 1f else 0f, tween(FadeMs), label = "key-lit")
    val press by animateFloatAsState(if (pressed) 1f else 0f, tween(80), label = "key-press")

    val numberColor by animateColorAsState(
        when {
            lit && lamp >= 0.6f -> NumberLit       // dark numeral on a bright amber window
            lit || paused -> NumberPaused          // light numeral when the window is dim
            else -> NumberIdle
        },
        tween(FadeMs), label = "number",
    )
    val labelColor by animateColorAsState(
        when { lit -> LabelLit; paused -> LabelPaused; labelEmpty -> LabelEmpty; else -> LabelIdle },
        tween(FadeMs), label = "label",
    )

    BoxWithConstraints(
        modifier
            .semantics(mergeDescendants = true) {
                this.contentDescription = contentDescription
                role = Role.Button
            }
            .combinedClickable(
                interactionSource = interaction,
                indication = null, // the artwork's own depth is the feedback
                onClick = onClick,
                onLongClick = onLongClick,
            ),
        contentAlignment = Alignment.Center,
    ) {
        // dp per artwork pixel: fit the artwork inside the space we are given, keeping its shape.
        val scale = minOf(maxWidth.value / art.width, maxHeight.value / art.height)
        val density = LocalDensity.current
        val artW = (art.width * scale).dp
        val artH = (art.height * scale).dp
        val travelPx = with(density) { (ChannelKeyArt.TRAVEL * scale).dp.toPx() }
        val pressPx = with(density) { (ChannelKeyArt.PRESS_EXTRA * scale).dp.toPx() }
        // The small two-line name: 6% of the wide key's width (the label window is 262 of its 560 px).
        val labelSize = with(density) { (art.label.w * scale * (0.060f * ChannelKeyArt.WIDTH / ChannelKeyArt.LABEL.w)).dp.toSp() }

        Box(Modifier.size(artW, artH).graphicsLayer { translationY = press * pressPx }) {
            Image(outArt, null, Modifier.fillMaxSize(), contentScale = ContentScale.FillBounds, alpha = 1f - latch, filterQuality = FilterQuality.High)
            Image(dimArt, null, Modifier.fillMaxSize(), contentScale = ContentScale.FillBounds, alpha = latch, filterQuality = FilterQuality.High)
            Image(litArt, null, Modifier.fillMaxSize(), contentScale = ContentScale.FillBounds, alpha = litLevel * lamp.coerceIn(0f, 1f), filterQuality = FilterQuality.High)

            // The live words move down with the artwork when it latches in.
            Box(Modifier.fillMaxSize().graphicsLayer { translationY = latch * travelPx }) {
                ArtText(art.number, scale) { window(numberColor, lit, (art.number.h * scale).dp) }
                ArtText(art.label, scale) {
                    if (bigLabel != null) {
                        // Just the value, as large as the window allows (e.g. minutes left).
                        val fontDp = ChannelKeyArt.fillFontSizeDp(bigLabel.length, art.label.w * scale, art.label.h * scale)
                        val fontSize = with(density) { fontDp.dp.toSp() }
                        Text(
                            text = bigLabel,
                            color = labelColor,
                            fontFamily = Condensed,
                            fontSize = fontSize,
                            lineHeight = fontSize,
                            textAlign = TextAlign.Center,
                            maxLines = 1,
                            softWrap = false,
                            // Digits only: trim the font's built-in padding so they sit centred in the window.
                            style = TextStyle(
                                platformStyle = PlatformTextStyle(includeFontPadding = false),
                                lineHeightStyle = LineHeightStyle(LineHeightStyle.Alignment.Center, LineHeightStyle.Trim.Both),
                                shadow = if (lit) Shadow(Color(0xFFFFA632).copy(alpha = 0.8f * lamp), Offset.Zero, 18f) else null,
                            ),
                            // The digits are taller than the window's line box: let them overflow it, centred.
                            modifier = Modifier.wrapContentSize(unbounded = true),
                        )
                    } else if (fitLabelLines > 0) {
                        // Full-screen mode: the name as large as fits the window, wrapped at spaces
                        // onto up to fitLabelLines lines, never scrolling.
                        val padDp = 8f
                        val measurer = rememberTextMeasurer()
                        val text = label.uppercase()
                        val fontDp = remember(text, art, scale, fitLabelLines, density) {
                            ChannelKeyArt.fitLabelFontDp(text, art.label.w * scale - 2 * padDp, art.label.h * scale, fitLabelLines) { line, dp ->
                                val sp = with(density) { dp.dp.toSp() }
                                val style = TextStyle(fontFamily = Condensed, fontSize = sp, letterSpacing = sp * 0.04f)
                                with(density) { measurer.measure(line, style, softWrap = false, maxLines = 1).size.width.toDp().value }
                            }
                        }
                        val fontSize = with(density) { fontDp.dp.toSp() }
                        Text(
                            text = text,
                            color = labelColor,
                            fontFamily = Condensed,
                            fontSize = fontSize,
                            lineHeight = fontSize * ChannelKeyArt.TALL_LINE_HEIGHT,
                            letterSpacing = fontSize * 0.04f,
                            textAlign = TextAlign.Center,
                            maxLines = fitLabelLines,
                            overflow = TextOverflow.Ellipsis,
                            style = TextStyle(
                                platformStyle = PlatformTextStyle(includeFontPadding = false),
                                shadow = if (lit) Shadow(Color(0xFFFFA632).copy(alpha = 0.8f * lamp), Offset.Zero, 24f) else null,
                                // Greedy wrapping, as fitLabelFontDp assumes.
                                lineBreak = LineBreak.Simple,
                                // Lines exactly lineHeight apart, without the font's extra leading above
                                // the first and below the last...
                                lineHeightStyle = LineHeightStyle(LineHeightStyle.Alignment.Center, LineHeightStyle.Trim.Both),
                            ),
                            // ...and never clipped to the window's height, which would drop the last line.
                            modifier = Modifier.fillMaxWidth().padding(horizontal = padDp.dp).wrapContentHeight(unbounded = true),
                        )
                    } else if (bigScrollingLabel) {
                        // One-big-button mode: the name as large as the window comfortably allows, on one line;
                        // a name too long for the glass scrolls slowly (like the panel's readout windows).
                        val fontDp = ChannelKeyArt.bigLabelFontDp(art.label.h * scale)
                        val fontSize = with(density) { fontDp.dp.toSp() }
                        Text(
                            text = label.uppercase(),
                            color = labelColor,
                            fontFamily = Condensed,
                            fontSize = fontSize,
                            lineHeight = fontSize * 1.1f,
                            letterSpacing = fontSize * 0.04f,
                            textAlign = TextAlign.Center,
                            maxLines = 1,
                            softWrap = false,
                            overflow = TextOverflow.Clip,
                            style = if (lit) TextStyle(shadow = Shadow(Color(0xFFFFA632).copy(alpha = 0.8f * lamp), Offset.Zero, 16f)) else TextStyle.Default,
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(horizontal = 6.dp)
                                .basicMarquee(iterations = Int.MAX_VALUE, initialDelayMillis = 1500, repeatDelayMillis = 1500, velocity = 36.dp),
                        )
                    } else Text(
                        text = label.uppercase(),
                        color = labelColor,
                        fontFamily = CondensedMedium,
                        fontSize = labelSize,
                        lineHeight = labelSize * 1.12f,
                        letterSpacing = labelSize * 0.05f,
                        textAlign = TextAlign.Center,
                        maxLines = 2,
                        overflow = TextOverflow.Ellipsis,
                        style = if (lit) TextStyle(shadow = Shadow(Color(0xFFFFA632).copy(alpha = 0.8f * lamp), Offset.Zero, 14f)) else TextStyle.Default,
                    )
                }
            }
        }
    }
}

/** Centres [content] inside the artwork window [rect] (sprite pixels), scaled by [scale] dp per pixel. */
@Composable
private fun ArtText(rect: ArtRect, scale: Float, content: @Composable () -> Unit) {
    Box(
        Modifier
            .offset((rect.x * scale).dp, (rect.y * scale).dp)
            .size((rect.w * scale).dp, (rect.h * scale).dp),
        contentAlignment = Alignment.Center,
    ) { content() }
}
